import { MdWaterDrop, MdFitnessCenter } from 'react-icons/md';
import { IoMdNutrition } from 'react-icons/io';

export const uploadData = [
    {
        type: 'latestUpload',
        items: [
            {
                id: 1,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/F5h75nb/1.png',
            },
        ],
    },

    {
        type: 'event',
        items: [
            {
                id: 1,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 2,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 3,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 4,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 5,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 6,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 7,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 8,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
        ],
    },

    {
        type: 'video',
        items: [
            {
                id: 1,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 2,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 3,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 4,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 3 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 5,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 4 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 6,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 7,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 8,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
        ],
    },

    {
        type: 'discussions',
        items: [
            {
                id: 1,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 1 here Title here Title here Title here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 2,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 3,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 4,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 3 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 5,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 6,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 4 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 7,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 5 here Title here Title here Title here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 8,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 9,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 6 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 10,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 7 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 11,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 8 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 12,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 9 here Title here Title here Title here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 13,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 14,
                category: 'training',
                categoryIcon: <MdFitnessCenter />,
                title: 'Title 10 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/TtXXtq6/2.png',
            },
            {
                id: 15,
                category: 'peds',
                categoryIcon: <MdWaterDrop />,
                title: 'Title 11 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
            {
                id: 16,
                category: 'nutrition',
                categoryIcon: <IoMdNutrition />,
                title: 'Title 2 here',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                image: 'https://i.ibb.co/VxNFydV/3.png',
            },
        ],
    },
];
